namespace Server.Api.Controllers.Orders;

public sealed record GetOrdersRequest(
    string? Cursor,
    string? SortBy,
    string? SortDirection,
    string? OrderNumberFilter,
    string? StatusFilter,
    decimal? MinTotalAmount,
    decimal? MaxTotalAmount,
    string? TrackingNumberFilter,
    DateTime? CreatedAfter,
    DateTime? CreatedBefore,
    DateTime? ConfirmedAfter,
    DateTime? ConfirmedBefore,
    DateTime? ShippedAfter,
    DateTime? ShippedBefore,
    DateTime? DeliveredAfter,
    DateTime? DeliveredBefore,
    decimal? MinOutstandingAmount,
    decimal? MaxOutstandingAmount,
    DateTime? EstimatedDeliveryAfter,
    DateTime? EstimatedDeliveryBefore,
    bool? HasPayment,
    bool? IsFullyPaid,
    bool? HasOutstandingBalance,
    string? ProductNameFilter,
    Guid? ProductIdFilter,
    string? ClientEmailFilter,
    string? ClientNameFilter,
    string? PaymentStatusFilter,
    int PageSize = 10);
